import { userDepsTemplate } from './userDepsTemplate';

const globalImports = [
  '/Users/ovidiu/cosmos/src/polyfills.ts',
  '/Users/ovidiu/cosmos/src/global.css',
];

const fixturePaths = [
  '/Users/ovidiu/cosmos/src/Counter/Counter.fixture.tsx',
  '/Users/ovidiu/cosmos/src/CounterButton/CounterButton.fixture.tsx',
];

const decoratorPaths = ['/Users/ovidiu/cosmos/src/cosmos.decorator.tsx'];

const rendererConfig = { port: 5002 };

it('should generate user deps module with absolute paths', () => {
  expect(
    userDepsTemplate({
      globalImports,
      fixturePaths,
      decoratorPaths,
      rendererConfig,
      rootDir: '/Users/ovidiu/cosmos/',
      relativeToDir: null,
    })
  ).toMatchInlineSnapshot(`
    "// This file is automatically generated by Cosmos. Add it to .gitignore and
    // only edit if you know what you're doing.

    // Keeping global imports here is superior to making them bundle entry points
    // because this way they become hot-reloadable.
    import '/Users/ovidiu/cosmos/src/polyfills.ts';
    import '/Users/ovidiu/cosmos/src/global.css';

    import fixture0 from '/Users/ovidiu/cosmos/src/Counter/Counter.fixture.tsx';
    import fixture1 from '/Users/ovidiu/cosmos/src/CounterButton/CounterButton.fixture.tsx';

    import decorator0 from '/Users/ovidiu/cosmos/src/cosmos.decorator.tsx';

    export const rendererConfig = {
      \\"port\\": 5002
    };

    export const fixtures = {
      'src/Counter/Counter.fixture.tsx': fixture0,
      'src/CounterButton/CounterButton.fixture.tsx': fixture1
    };

    export const decorators = {
      'src/cosmos.decorator.tsx': decorator0
    };
    "
  `);
});

it('should generate user deps module with relative paths', () => {
  expect(
    userDepsTemplate({
      globalImports,
      fixturePaths,
      decoratorPaths,
      rendererConfig,
      rootDir: '/Users/ovidiu/cosmos',
      relativeToDir: '/Users/ovidiu/cosmos/src',
    })
  ).toMatchInlineSnapshot(`
    "// This file is automatically generated by Cosmos. Add it to .gitignore and
    // only edit if you know what you're doing.

    // Keeping global imports here is superior to making them bundle entry points
    // because this way they become hot-reloadable.
    import './polyfills.ts';
    import './global.css';

    import fixture0 from './Counter/Counter.fixture.tsx';
    import fixture1 from './CounterButton/CounterButton.fixture.tsx';

    import decorator0 from './cosmos.decorator.tsx';

    export const rendererConfig = {
      \\"port\\": 5002
    };

    export const fixtures = {
      'src/Counter/Counter.fixture.tsx': fixture0,
      'src/CounterButton/CounterButton.fixture.tsx': fixture1
    };

    export const decorators = {
      'src/cosmos.decorator.tsx': decorator0
    };
    "
  `);
});
