// @flow

import path from 'path';
import { createServer as createHttpServer } from 'http';
import promisify from 'util.promisify';
import express from 'express';
import httpProxyMiddleware from 'http-proxy-middleware';
import launchEditor from 'react-dev-utils/launchEditor';
import getPlaygroundHtml from './playground-html';

import type { Config } from 'react-cosmos-flow/config';

export function createServerApp(cosmosConfig: Config) {
  const { httpProxy } = cosmosConfig;
  const app = express();

  if (httpProxy) {
    const { context, target } = httpProxy;
    app.use(context, httpProxyMiddleware(target));
  }

  const playgroundHtml = getPlaygroundHtml(cosmosConfig);
  app.get('/', (req: express$Request, res: express$Response) => {
    res.send(playgroundHtml);
  });

  app.get('/_playground.js', (req: express$Request, res: express$Response) => {
    res.sendFile(require.resolve('react-cosmos-playground'));
  });

  app.get('/_cosmos.ico', (req: express$Request, res: express$Response) => {
    res.sendFile(path.join(__dirname, 'static/favicon.ico'));
  });

  return app;
}

export function createServer(cosmosConfig: Config, app: express$Application) {
  const { port, hostname } = cosmosConfig;
  const server = createHttpServer(app);

  async function startServer() {
    const listen = promisify(server.listen.bind(server));
    await listen(port, hostname);

    const hostnameDisplay = hostname || 'localhost';
    console.log(`[Cosmos] See you at http://${hostnameDisplay}:${port}/`);
  }

  async function stopServer() {
    await promisify(server.close.bind(server))();
  }

  return { startServer, stopServer };
}

export function serveStaticDir(
  app: express$Application,
  publicUrl: string,
  publicPath: string
) {
  const relPublicPath = path.relative(process.cwd(), publicPath);
  console.log(`[Cosmos] Serving static files from ${relPublicPath}`);

  app.use(
    publicUrl,
    express.static(publicPath, {
      // Ensure loader index (generated by html-webpack-plugin) loads instead
      // of the index.html from publicPath
      index: false
    })
  );
}

export function attachStackFrameEditorLauncher(app: express$Application) {
  app.get(
    '/__open-stack-frame-in-editor',
    (req: express$Request, res: express$Response) => {
      launchEditor(req.query.fileName, req.query.lineNumber);
      res.end();
    }
  );
}
