import path from 'path';
import { writeFile } from 'fs';
import promisify from 'util.promisify';
import { CosmosConfig } from '../shared/config';
import { getCompiledUserDeps } from '../shared/userDeps';

const writeFileAsync = promisify(writeFile);

export async function generateUserDepsFile(cosmosConfig: CosmosConfig) {
  const { userDepsPath, port } = cosmosConfig;

  const compiledModulesDeps = await getCompiledUserDeps(cosmosConfig, { port });
  const fileContents = getCompiledTemplate(compiledModulesDeps);
  await writeFileAsync(userDepsPath, fileContents, 'utf8');

  const relModulesPath = path.relative(process.cwd(), userDepsPath);
  console.log(`[Cosmos] Generated ${relModulesPath}`);
}

function getCompiledTemplate(userDeps: string) {
  return `// This file is automatically generated by Cosmos. Best ignore it.
module.exports = ${userDeps};`;
}
