import React, { Component } from 'react';

import './Counter.css';

export default class Counter extends Component {
  state = {
    value: 0,
  };

  onButtonClick = () => {
    // This breakpoint is intentional. The purpose of this example is to
    // test if sourcemaps are properly generated by the Cosmos build
    // eslint-disable-next-line no-debugger
    debugger;
    this.setState({
      value: this.state.value + 1,
    });
  };

  render() {
    return (
      <button className="CounterButton" onClick={this.onButtonClick}>
        {`Clicked ${this.state.value} times`}
      </button>
    );
  }
}
