name: docs
on:
  pull_request:
  push:
    branches: main
jobs:
  build-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: .npm-cache
          key: '${{ runner.os }}-npm'

      - run: npm ci --cache .npm-cache
      - run: npm run build
      - run: npm --workspace example-todo run export

      - uses: actions/upload-artifact@v4
        with:
          name: demo-cosmos-export
          path: ./examples/todo/cosmos-export

  publish-docs:
    runs-on: ubuntu-latest
    needs: build-demo
    defaults:
      run:
        working-directory: docs
    permissions:
      contents: read
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ./docs/.npm-cache
          key: '${{ runner.os }}-npm-docs'

      - run: npm ci --cache .npm-cache
      - run: npm run check-types
      # TODO: Add linting step once docs linting is decoupled from main package
      # Revisit linting configs when upgrading Next & Nextra.
      - run: npm run build

      - uses: actions/download-artifact@v4
        with:
          name: demo-cosmos-export
          path: ./docs/out/demo

      - uses: cloudflare/wrangler-action@v3
        if: env.CLOUDFLARE_API_TOKEN != ''
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./docs
          command: pages deploy ./out --project-name=react-cosmos-docs --branch=${{ github.head_ref || github.ref_name }}

      # Forks don't have access to secrets and can't deploy to Cloudflare.
      # Instead, we upload the docs build as an artifact, which can be downloaded
      # and reviewed by maintainers locally.
      - uses: actions/upload-artifact@v4
        if: env.CLOUDFLARE_API_TOKEN == ''
        with:
          name: react-cosmos-docs
          path: ./docs/out
