name: docs
on:
  pull_request:
  push:
    branches: main
jobs:
  build-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: .npm-cache
          key: '${{ runner.os }}-npm'

      - run: npm ci --cache .npm-cache
      - run: npm run build
      - run: npm --workspace example-todo run export

      - uses: actions/upload-artifact@v4
        with:
          name: demo-cosmos-export
          path: ./examples/todo/cosmos-export

  # publish-website: (rename job, too?)
  publish-docs:
    runs-on: ubuntu-latest
    needs: build-demo
    defaults:
      run:
        working-directory: docs
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ./docs/.npm-cache
          key: '${{ runner.os }}-npm-docs'

      - run: npm ci --cache .npm-cache
      - run: npm run build

      - uses: actions/download-artifact@v4
        with:
          name: demo-cosmos-export
          path: ./docs/out/demo

      - run: git status

      - uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./docs
          command: pages deploy ./out --project-name=react-cosmos-website

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wranger-logs
          path: /home/runner/.config/.wrangler/logs/
