name: release-canary
on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    if: ${{ !contains(github.event.head_commit.message, '[release]') }}
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/cache@v5
        id: npm-cache
        with:
          path: .npm-cache
          key: '${{ runner.os }}-npm'

      - run: npm ci --cache .npm-cache
      - run: npm run release:check

      - run: npm run release:canary
